force-app/main/default/objects/Maintenance_Check__c/Maintenance_Check__c.object-meta.xml
<CustomObject>
    <label>Maintenance Check</label>
    <nameField>
        <displayFormat>Maint-{0000}</displayFormat>
        <label>Maintenance Check No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Check__c/fields/Fuel_Level__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Level__c</fullName>
    <label>Fuel Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Maintenance_Check__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <formula>Plane__r.Mileage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Check__c/fields/Plane__c.field-meta.xml
<CustomField>
    <fullName>Plane__c</fullName>
    <label>Plane</label>
    <referenceTo>Plane__c</referenceTo>
    <relationshipLabel>Maintenance Checks</relationshipLabel>
    <relationshipName>Maintenance_Checks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plane__c/Plane__c.object-meta.xml
<CustomObject>
    <label>Plane</label>
    <nameField>
        <label>Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InspectionFlowMethods.cls
public with sharing class InspectionFlowMethods {
	
    @AuraEnabled
    public static Maintenance_Check__c InitMaintenanceCheck(String planeID){
        System.debug(planeID);
        return new Maintenance_Check__c (Plane__c=planeID,Fuel_Level__c=50);
    }
    
    @InvocableMethod(label='update Plane')
    public static void updatePlane(List<PlaneId> planes){
    List<Plane__c> planeList = new List<Plane__c>();    
    for(PlaneId pid : planes){
      Plane__c plane = new Plane__c();
      plane.Id = pid.recordId;
      plane.Mileage__c = Long.valueOf(pid.mileage);
      planeList.add(plane);
     }
    update planeList;
    }
    
    public class PlaneId {
        @InvocableVariable(label='recordId' required=true)
		public Id recordId;

        @InvocableVariable(label='Mileage' required=true)
		public String mileage;


    }
}