force-app/main/default/objects/Maintenance_Check__c/Maintenance_Check__c.object-meta.xml
<CustomObject>
    <label>Maintenance Check</label>
    <nameField>
        <displayFormat>Maint-{0000}</displayFormat>
        <label>Maintenance Check No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Check__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <formula>Plane__r.Mileage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Check__c/fields/Plane__c.field-meta.xml
<CustomField>
    <fullName>Plane__c</fullName>
    <label>Plane</label>
    <referenceTo>Plane__c</referenceTo>
    <relationshipLabel>Maintenance Checks</relationshipLabel>
    <relationshipName>Maintenance_Checks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plane__c/Plane__c.object-meta.xml
<CustomObject>
    <label>Plane</label>
    <nameField>
        <label>Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plane__c/fields/Flight_Hours__c.field-meta.xml
<CustomField>
    <fullName>Flight_Hours__c</fullName>
    <label>Flight Hours</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InspectionFlowMethodsTest.cls
@isTest

public class InspectionFlowMethodsTest {
    
    static testMethod void testFlowMethods(){
        Plane__c testPlane = new Plane__c(name='testPlane');
        testPlane.Flight_Hours__c =15000.00;
        testPlane.Mileage__c = 88387828.00;
        test.startTest();
        insert testPlane;
        test.stopTest();
        List<InspectionFlowMethods.PlaneId> planeList = new List<InspectionFlowMethods.PlaneId>();
        InspectionFlowMethods.PlaneId pid = new InspectionFlowMethods.PlaneId();
        pid.recordId = testPlane.Id;
        pid.mileage = String.valueOf(testPlane.Mileage__c);
        planeList.add(pid);
        String planeId = (String)testPlane.Id;
        Maintenance_Check__c maintcheck = InspectionFlowMethods.InitMaintenanceCheck(planeId);
        InspectionFlowMethods.updatePlane(planeList);
       
    }

}